# Generated by Django 2.2.2 on 2019-06-16 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='how_can_help',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='gender',
            field=models.CharField(choices=[('Dev', 'Desenvolvedor'), ('Des', 'Designer'), ('Out', 'Outro')], default='isso', max_length=2),
            preserve_default=False,
        ),
    ]
