# Generated by Django 2.2.2 on 2019-06-16 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20190616_1210'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacancy',
            old_name='gender',
            new_name='how_help',
        ),
    ]
