# Generated by Django 2.2.2 on 2019-06-16 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20190616_1211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='name',
        ),
    ]
